#pragma config(Sensor, S1,     left,                sensorLightActive)
#pragma config(Sensor, S2,     right,               sensorLightActive)
#pragma config(Sensor, S3,     sonar,               sensorSONAR)
#pragma config(Sensor, S4,     touch,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void rain()
{
	int a,b,musi;
	int flog=0;
	musi=0;
	int av=36,bv=34;

	while(1)
	{
		a=SensorValue(left);
		b=SensorValue(right);
		if(a>av && b>bv)
		{
			motor[motorA]=motor[motorC]=80;
			flog=0;
		}
		if(a>av && b<bv)
		{
			motor[motorA]=90;
			motor[motorC]=-20;
			flog=0;
		}
		if(a<av && b>bv)
		{
			motor[motorA]=-20;
			motor[motorC]=90;
			flog=0;
		}
		if(a<av && b<bv)
		{
			if(flog==0)
			{
			  flog=1;
			  musi++;

			}
			if(musi<=8)
			{
				motor[motorA]=motor[motorC]=70;
				wait1Msec(1);
				PlaySound(soundBeepBeep);
				wait1Msec(200);
			}
			if(musi>8)
			{
				motor[motorA]=motor[motorC]=0;
				break;
		  }
		}
	}
}
void rain2()
{
	int a,b,musi;
	int flog=0;
	musi=0;
	int av=36,bv=34;

	while(1)
	{
		a=SensorValue(left);
		b=SensorValue(right);
		if(a>av && b>bv)
		{
			motor[motorA]=motor[motorC]=80;
			flog=0;
		}
		if(a>av && b<bv)
		{
			motor[motorA]=80;
			motor[motorC]=-20;
			flog=0;
		}
		if(a<av && b>bv)
		{
			motor[motorA]=-20;
			motor[motorC]=80;
			flog=0;
		}
		if(a<av && b<bv)
		{
			if(flog==0)
			{
			  flog=1;
			  musi++;

			}
			if(musi<=3)
			{
				motor[motorA]=motor[motorC]=70;
				wait1Msec(1);
				PlaySound(soundBeepBeep);
				wait1Msec(200);
			}
			if(musi>3)
			{
				motor[motorA]=motor[motorC]=0;
				break;
		  }
		}
	}
}
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void left1()
{
	motor[motorA]=0;
	motor[motorC]=40;
	wait1Msec(650);
}
void go()
{
	motor[motorA]=80;
	motor[motorC]=80;
	wait1Msec(500);
}

void right1()
{
	motor[motorA]=40;
	motor[motorC]=0;
	wait1Msec(650);
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void sosol()
{
	while(1)
	{
		 motor[motorA]=0;
	   motor[motorC]=35;
	   if(SensorValue(sonar) < 38 )
	   {
	     PlaySound(soundBeepBeep);
	     motor[motorA]=0;
	     motor[motorC]=0;
	     break;
	   }
  }
}
void sosor()
{
	while(1)
	{
		 motor[motorA]=35;
	   motor[motorC]=0;
	   if(SensorValue(sonar) < 38)
	   {
	     PlaySound(soundBeepBeep);
	     motor[motorA]=40;
	     motor[motorC]=-40;
	     break;
	   }
  }
}
task main()
{
  rain();
  sosor();
  right1();
  sosor();
  left1();
  sosol();
  right1();
  right1();
  rain2();
}
