#pragma config(Sensor, S1,     left,                sensorLightActive)
#pragma config(Sensor, S2,     right,               sensorLightActive)
#pragma config(Sensor, S3,     sonar,               sensorSONAR)
#pragma config(Sensor, S4,     touch,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int left_s, right_s ;
int left_t, right_t;
int count=0;
int min=255;
int a=0,p1=0;

task main()
{
	left_t = SensorValue(left) + 7;
	right_t = SensorValue(right) + 7;

	nMotorEncoder[motorA] = 0;
	while(nMotorEncoder[motorA] < 100)
	{
		motor[motorA] = 90;
		motor[motorC] = 90;
	}
	while(true)
	{
		left_s = SensorValue(left);
		right_s = SensorValue(right);

		if(left_s > left_t && right_s > right_t)
		{
			motor[motorA] = 90;
			motor[motorC] = 90;
		}
		else if(left_s > left_t && right_s < right_t)
		{
			motor[motorA] = 90;
			motor[motorC] = -50;
		}
		else if(left_s < left_t && right_s > right_t)
		{
			motor[motorA] = -50;
			motor[motorC] = 90;
		}
		else if(left_s < left_t && right_s < right_t)
		{
			if(count<8)
			{
				motor[motorA] = 90;
				motor[motorC] = 90;
				wait1Msec(100);
				PlaySound(soundBeepBeep);
				wait1Msec(200);
				count+=1;
			}
			else if(count>=8)
			{
				motor[motorA] = 90;
				motor[motorC] = 90;
				wait1Msec(100);
				break;
			}
		}
	}

	nMotorEncoder[motorA] = 0;
  while(nMotorEncoder[motorA] > -250)
  {
  	motor[motorA] = -50;
  	motor[motorC] = 50;
  }

  nMotorEncoder[motorA] = 0;
  while(nMotorEncoder[motorA] > -250)
  {
  	motor[motorA] = 50;
    motor[motorC] = -50;

  	p1 = SensorValue(sonar);

  	if(min > a)
  	{
  		min = a;
  	  p1 = nMotorEncoder[motorC];
  	}
  }

  while(nMotorEncoder[motorA] > p1 - 200)
  {
  	motor[motorA] = -50;
  	motor[motorC] = 50;
  }

  nMotorEncoder[motorA] = 0;
  while(nMotorEncoder[motorA] < 700)
  {
  	motor[motorA] = 70;
  	motor[motorC] = 70;
  }
  while(true)
	{
		left_s = SensorValue(left);
		right_s = SensorValue(right);

		if(left_s > left_t && right_s > right_t)
		{
			motor[motorA] = 90;
			motor[motorC] = 90;
		}
		else if(left_s > left_t && right_s < right_t)
		{
			motor[motorA] = 90;
			motor[motorC] = -50;
		}
		else if(left_s < left_t && right_s > right_t)
		{
			motor[motorA] = -50;
			motor[motorC] = 90;
		}
		else if(left_s < left_t && right_s < right_t)
		{
			if(count<4)
			{
				motor[motorA] = 90;
				motor[motorC] = 90;
				wait1Msec(100);
				PlaySound(soundBeepBeep);
				wait1Msec(200);
				count+=1;
			}
			else if(count>=4)
			{
				motor[motorA] = 90;
				motor[motorC] = 90;
				wait1Msec(200);
				break;
			}
		}
	}
}
