#pragma config(Sensor, S1,     left,                sensorLightActive)
#pragma config(Sensor, S2,     right,               sensorLightActive)
#pragma config(Sensor, S3,     sonar,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int l,r;

task main()
{
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(5000);

	while(true)
	{
    l = SensorValue[left];
    r = SensorValue[right];

    if(l < 40 && r < 40)
    {
    	nMotorEncoder[motorA] = 0;
    	while(nMotorEncoder[motorA] > -300)
    	{
    		motor[motorA] = -80;
    		motor[motorC] = -80;
    	}

    	nMotorEncoder[motorA] = 0;
    	while(nMotorEncoder[motorA] < 300)
    	{
    		motor[motorA] = 80;
    		motor[motorC] = -80;
    	}
    }
    else if (l < 40 && r > 40)
    {
    	motor[motorA] = -80;
    	motor[motorC] = 80;
    }
    else if(l > 40 && r < 40)
    {
    	motor[motorA] = 80;
    	motor[motorC] = -80;
    }
    else if(l > 40 && r > 40)
    {
    	motor[motorA] = 80;
    	motor[motorC] = 80;
    }
	}
}
