#pragma config(Sensor, S1,     left,                sensorLightActive)
#pragma config(Sensor, S2,     right,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int l,r;
int count;

void pro1()
{
	nMotorEncoder[motorB] = 0;
	while(nMotorEncoder[motorB] < 350)
	{
	  	motor[motorB] = 90;
	}
}

void pro2()
{
	nMotorEncoder[motorB] = 0;
	while(nMotorEncoder[motorB] > -350)
	  {
		  motor[motorB] = -80;
	  }
}
task main()
{
	l = SensorValue(left) + 7;
  r = SensorValue(right) + 7;

	nMotorEncoder[motorA] = 0;
  while(nMotorEncoder[motorA] < 1000)
  {
  	motor[motorA] = 100;
  	motor[motorC] = 100;
  }

  while(true)
  {
  	if(SensorValue(left) > l && SensorValue(right) > r)
  	{
  	  motor[motorA] = 100;
  	  motor[motorC] = 100;
  	}
  	else if(SensorValue(left) > l && SensorValue(right) < r)
  	{
  		motor[motorA] = 100;
  		motor[motorC] = 20;
    }
    else if(SensorValue(left) < l && SensorValue(right) > r)
  	{
  		motor[motorA] = 20;
  		motor[motorC] = 100;
    }
    else if(SensorValue(left) < l && SensorValue(right) < r)
    {
    	break;
    }
  }

  nMotorEncoder[motorA] = 0;
  while(nMotorEncoder[motorA] < 800)
  {
  	motor[motorA] = 100;
  	motor[motorC] = 100;
  }

	while(true)
	{
    pro1();
    pro2();
    count += 1;
    if(count > 15) break;
  }

  while(true)
  {
  	motor[motorA] = -100;
  	motor[motorC] = -100;
  	if(SensorValue(left) < l || SensorValue(right) < r)
  	{
  		motor[motorA] = 0;
  		motor[motorC] = 0;
  		wait1Msec(300);
  		break;
  	}
  }

  nMotorEncoder[motorC] = 0;
  while(nMotorEncoder[motorC] < 600)
  {
  	motor[motorA] = -70;
  	motor[motorC] = 100;
  }

  nMotorEncoder[motorA] = 0;
  while(true)
  {
  	if(SensorValue(left) > l && SensorValue(right) > r)
  	{
  	  motor[motorA] = 90;
  	  motor[motorC] = 90;
  	}
  	else if(SensorValue(left) > l && SensorValue(right) < r)
  	{
  		motor[motorA] = 90;
  		motor[motorC] = -100;
    }
    else if(SensorValue(left) < l && SensorValue(right) > r)
  	{
  		motor[motorA] = -100;
  		motor[motorC] = 90;
    }
    else if(SensorValue(left) < l && SensorValue(right) < r)
    {
    	nMotorEncoder[motorA] = 0;
    	while(nMotorEncoder[motorA] < 100)
    	{
    		motor[motorA] = 100;
    		motor[motorC] = 100;
    	}
    	if(SensorValue(left) < l && SensorValue(right) < r)
    	{
    		nMotorEncoder[motorA] = 0;
    		while(nMotorEncoder[motorA] < 500)
    		{
    			motor[motorA] = 100;
    		  motor[motorC] = 100;
    		}
    		break;
    	}
    	else
    	{
    	  nMotorEncoder[motorA] = 0;
    		while(nMotorEncoder[motorA] > -150)
    		{
    			motor[motorA] = -80;
    		  motor[motorC] = -100;
    		}
    	}
    }
  }
}
