#pragma config(Sensor, S1,     left,                sensorLightActive)
#pragma config(Sensor, S2,     right,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int l,r;
int count;
l = SensorValue(left) + 7;
r = SensorValue(right) + 7;

task main()
{
	nMotorEncoder[motorA] = 0;
  while(nMotorEncoder[motorA] < 1000)
  {
  	motor[motorA] = 100;
  	motor[motorC] = 100;
  }

  while(true)
  {
  	if(SensorValue(left) > l && SensorValue(right) > r)
  	{
  	  motor[motorA] = 100;
  	  motor[motorC] = 100;
  	}
  	else if(SensorValue(left) > l && SensorValue(right) < r)
  	{
  		motor[motorA] = 100;
  		motor[motorC] = 60;
    }
    else if(SensorValue(left) < l && SensorValue(right) > r)
  	{
  		motor[motorA] = 60;
  		motor[motorC] = 100;
    }
    else if(SensorValue(left) < l && SensorValue(right) < r)
    {
    	break;
    }
  }

  nMotorEncoder[motorA] = 0;
  while(nMotorEncoder[motorA] < 1500)
  {
  	motor[motorA] = 100;
  	motor[motorC] = 100;
  }

  // ...

  while(true)
  {
  	motor[motorA] = -100;
  	motor[motorC] = -100;
  	if(SensorValue(left) < l && SensorValue(right) < r)
  	{
  		while(SensorValue(right) < r)
  		{
  			motor[motorC] = 100;
  		}
  		break;
  	}
  }

  while(true)
  {
  	motor[motorC] = 100;

  	if(SensorValue(right) < r)
  	{
  		while(SensorValue(left) > l)
  		{
  			motor[motorA] = -100;
  		}
  		break;
  	}
  }

  nMotorEncoder[motorA] = 0;

  while(true)
  {
  	motor[motorA] = 100;
  	motor[motorC] = 100;
  	if(SensorValue(left) > l && SensorValue(right) > r)
    {
    	while(SensorValue(left) > l)
    	{
    		motor[motorA] = 100;
  	    motor[motorC] = 100;
    	}
    	while(nMotorEncoder[motorA] < 1000)
    	{
    		motor[motorA] = -100;
  	    motor[motorC] = -100;
    	}
    	while(true)
    	{
    		if(SensorValue(left) < l && SensorValue(right) < r)
  	    {
  	    	break;
  	    }
  	    else if(SensorValue(left) > l && SensorValue(right) < r)
  	    {
  	    	motor[motorA] = -100;
  	    }
  	    else if(SensorValue(left) < l && SensorValue(right) > r)
  	    {
  	    	motor[motorC] = 100;
  	    }
  	    else if(SensorValue(left) > l && SensorValue(right) > r)
  	    {
  	    	motor[motorA] = 100;
  	    	motor[motorC] = -100;
  	    }
    	}
    	break;
    }
  }

  nMotorEncoder[motorA] = 0;
  while(true)
  {
  	motor[motorA] = 100;
  	motor[motorC] = 100;

  	if(nMotorEncoder[motorA] > 8000)
  	{
  		while(true)
  		{
  			if(SensorValue(left) > l && SensorValue(right) > r)
  	    {
  	      motor[motorA] = 100;
  	      motor[motorC] = 100;
  	    }
  	    else if(SensorValue(left) > l && SensorValue(right) < r)
  	    {
  		    motor[motorA] = 100;
  		    motor[motorC] = 40;
        }
        else if(SensorValue(left) < l && SensorValue(right) > r)
  	    {
  		    motor[motorA] = 40;
  		    motor[motorC] = 100;
        }
        else if(SensorValue(left) < l && SensorValue(right) < r)
        {
        	nMotorEncoder[motorA] = 0;
    	    if(count==0)
    	    {
    	    	while(nMotorEncoder[motorA] < 700)
    	    	{
    	    		motor[motorA] = 100;
    	    	}
    	    	nMotorEncoder[motorA] = 0;
    	    	while(nMotorEncoder[motorA] < 500)
    	    	{
    	    		motor[motorA] = 100;
  	          motor[motorC] = 100;
    	    	}
    	    }
    	    else
    	    {
    	    	while(SensorValue(left) < l && SensorValue(right) < r)
    	    	{
    	    		motor[motorA] = 100;
  	          motor[motorC] = 100;
    	    	}
    	    	break;
    	    }
        }
  	  }
  	}
  	break;
  }
}
