#pragma config(Sensor, S1,     left,                sensorLightActive)
#pragma config(Sensor, S2,     right,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int l,r;
int count,a;
task main()
{

	l = SensorValue[left] + 7;
	r = SensorValue[right] + 7;

	nMotorEncoder[motorA] = 0;
	while(true)
  {
  	if(nMotorEncoder[motorA] > 1000) break;
  	motor[motorA] = 100;
  	motor[motorC] = 97;
  }
  nMotorEncoder[motorA] = 0;
  while(true)
  {
  	if(SensorValue[left] > l && SensorValue[right] > r)
  	{
  	  motor[motorA] = 100;
  	  motor[motorC] = 97;
  	}
  	else if(SensorValue[left] > l && SensorValue[right] < r)
  	{
  		motor[motorA] = 100;
  		motor[motorC] = 10;
    }
    else if(SensorValue[left] < l && SensorValue[right] > r)
  	{
  		motor[motorA] = 10;
  		motor[motorC] = 100;
    }
    else if(SensorValue[left] < l && SensorValue[right] < r)
    {
    	if(nMotorEncoder[motorA] > 5000)
    	{
    		break;
    	}
    	else
    	{
    		motor[motorA] = 100;
  	    motor[motorC] = 97;
    	}
    }
  }
  nMotorEncoder[motorA] = 0;
  while(nMotorEncoder[motorA] < 800)
  {
  	motor[motorA] = 100;
  	motor[motorC] = 97;
  }
  nMotorEncoder[motorB] = 0;
	  while(nMotorEncoder[motorB] > -20)
	  {
		  motor[motorB] = -50;
	  }

  while(true)
  {
  	l = SensorValue(left);
    r = SensorValue(right);
  	motor[motorA] = -97;
  	motor[motorC] = -100;
  	if(SensorValue[left] < l && SensorValue[right] < r)
  	{
  		motor[motorA] = 0;
  		motor[motorC] = 0;
  		wait1Msec(300);
  		break;
  	}
  }

  nMotorEncoder[motorC] = 0;
  while(nMotorEncoder[motorC] < 500)
  {
  	motor[motorA] = -50;
  	motor[motorC] = 100;
  }

  nMotorEncoder[motorA] = 0;
  while(true)
  {
  	l = SensorValue(left);
    r = SensorValue(right);
  	if(SensorValue[left] > l && SensorValue[right] > r)
  	{
  	  motor[motorA] = 100;
  	  motor[motorC] = 97;
  	}
  	else if(SensorValue[left] > l && SensorValue[right] < r)
  	{
  		motor[motorA] = 100;
  		motor[motorC] = -100;
    }
    else if(SensorValue[left] < l && SensorValue[right] > r)
  	{
  		motor[motorA] = -100;
  		motor[motorC] = 100;
    }
    else if(SensorValue[left] < l && SensorValue[right] < r)
    {
    	if(nMotorEncoder[motorA] > 7000)
    	{
  		  break;
      }
    	else if(nMotorEncoder[motorA] > 5500)
    	{
    		motor[motorA] = 100;
  	    motor[motorC] = 97;
    	}
    	else
    	{
    		nMotorEncoder[motorC] = 0;
        while(nMotorEncoder[motorC] > -100)
        {
  	      motor[motorA] = -100;
  	      motor[motorC] = -100;
        }
    	}
    }
  }
}
